REAL(KIND=dp), INTENT(IN) ::  ch3o2,ethp,ro2,c2o3,ano2,nap,isopp,isopn,isopo2,xo2, &
                              pcg1_b_c,pcg2_b_c,pcg3_b_c,pcg4_b_c, &
                              pcg5_b_c,pcg6_b_c,pcg7_b_c,pcg8_b_c, &
                              pcg9_b_c,opcg1_b_c,opcg2_b_c,opcg3_b_c, &
                              opcg4_b_c,opcg5_b_c,opcg6_b_c,opcg7_b_c, &
                              opcg8_b_c,pcg1_b_o,pcg2_b_o,pcg3_b_o, &
                              pcg4_b_o,pcg5_b_o,pcg6_b_o,pcg7_b_o, &
                              pcg8_b_o,pcg9_b_o,opcg1_b_o,opcg2_b_o,&
                              opcg3_b_o,opcg4_b_o,opcg5_b_o,opcg6_b_o,&
                              opcg7_b_o,opcg8_b_o,pcg1_f_c,pcg2_f_c,&
                              pcg3_f_c,pcg4_f_c,pcg5_f_c,pcg6_f_c,&
                              pcg7_f_c,pcg8_f_c,pcg9_f_c,opcg1_f_c,&
                              opcg2_f_c,opcg3_f_c,opcg4_f_c,opcg5_f_c,&
                              opcg6_f_c,opcg7_f_c,opcg8_f_c,pcg1_f_o,&
                              pcg2_f_o,pcg3_f_o,pcg4_f_o,pcg5_f_o,&
                              pcg6_f_o,pcg7_f_o,pcg8_f_o,pcg9_f_o,&
                              opcg1_f_o,opcg2_f_o,opcg3_f_o,opcg4_f_o,&
                              opcg5_f_o,opcg6_f_o,opcg7_f_o,opcg8_f_o,&
                              psd1,psd2

!
